version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
    "Stage 1":
        jobs:
          - hello/hello-build
    "Before script":
            - sfdx --version
    "During Script":
            - echo "This is stage 3, during script"
    "After Script":
            - sfdx plugins --core
            - echo "All steps ran successfully"