version: 2
jobs:
    build: #job name, Jobs are a collection of steps and each job must declare an executor that is either docker, machine, or macos.
        docker:
        - image: circleci/buildpack-deps:curl-browsers
		#the list of pre-built CircleCI images on dockerhubwhat is an image: https://circleci.com/docs/2.0/circleci-images/
        steps:
        - run: # Run step to execute commands, see circleci.com/docs/2.0/configuration-reference/#run
            name: "Step 3"
            command: echo "Hello ${CIRCLE_USERNAME}"
        - run:
            name: Step 4 - Show some of the CircleCI runtime env vars
            command: |-
                echo "TRIGGERER: ${CIRCLE_USERNAME}"
                echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
                echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
                echo "BRANCH: ${CIRCLE_BRANCH}"
                echo "RUNNING JOB: ${CIRCLE_JOB}"
                echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
                echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
    mytestjob:
        docker:
        - image: circleci/buildpack-deps:curl-browsers
        steps:
        - run:
            name: mytestjob Step 1 - Show system information        
            command: |-
                echo "uname:" $(uname -a)
                echo "arch: " $(arch)
        - run: 
            name: "mytestjob Step 2 - Testing"
            command: echo "test ends"
workflows: 
#Workflows define a list of jobs and their run order. It is possible to run jobs in parallel, sequentially, on a schedule, or 
#with a manual gate using an approval job.
  version: 2
  build_and_test:
    jobs:
      - build
      - mytestjob        