version: 2
jobs:
  build:
    docker:
        - image: circleci/openjdk:latest-node-browsers
    steps:
        - checkout
        - restore_cache:
            keys:
                - sfdx-6.8.2-local
        - run:
            name: Install Salesforce DX
            command: |
                if [ ! -d node_modules/sfdx-cli ]; then
                    export SFDX_AUTOUPDATE_DISABLE=true
                    export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                    export SFDX_DOMAIN_RETRY=300
                    npm install sfdx-cli@6.8.2
                    node_modules/sfdx-cli/bin/run --version
                    node_modules/sfdx-cli/bin/run plugins --core
                fi
        - save_cache:
            key: sfdx-6.8.2-local
            paths: 
                - node_modules
        - run: 
            name: Create Scratch Org
            command: |
                openssl aes-256-cbc -k $KEY -in access/server.key.enc -out access/server.key -d -md md5
                node_modules/sfdx-cli/bin/run force:auth:jwt:grant -i $HUB_CONSUMER_KEY -f ./access/server.key -u $HUB_SFDX_USER
                node_modules/sfdx-cli/bin/run force:org:create -s -f config/project-scratch-def.json -a VSCI_ScOrg
        - run:
            name: Remove Server Key
            when: always
            command: |
                rm access/server.key
        - run:
            name: Install Lightning Testing Service
            command: |
                node_modules/sfdx-cli/bin/run force:lightning:test:install -t jasmine
        - run: 
            name: Push Source
            command: |
                node_modules/sfdx-cli/bin/run force:source:push -u VSCI_ScOrg
        #- run:
            #name: Run Apex Tests
            #command: |
                #mkdir ~/tests
                #mkdir ~/tests/apex
                #node_modules/sfdx-cli/bin/run force:apex:test:run -u scratch -c -r human -d ~/tests/apex -w 9999
        - run:
            name: Run Lightning Tests
            command: | 
                mkdir ~/tests/lightning
                node_modules/sfdx-cli/bin/run force:lightning:test:run -d ~/tests/lightning -r human -a jasmineTests.app -o
        #- run: 
            #name: Push to Codecov.io (Optional Step)
            #command: |
                #cp ~/tests/apex/test-result-codecoverage.json .
                #bash <(curl -s https://codecov.io/bash)
        - run: 
            name: Clean Up
            when: always
            command: |
                node_modules/sfdx-cli/bin/run force:org:delete -u VSCI_ScOrg -p
                #rm ~/tests/apex/*.txt ~/tests/apex/test-result-7*.json
        - store_artifacts:
            path: ~/tests
        - store_test_results:
            path: ~/tests