version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
jobs:
    testjob:
        description: "A very simple command for demonstration purposes"
        parameters:
        to:
            type: string
            default: "Hello World"
        steps:
        - run: echo << parameters.to >>
